### ISSUE TITLE
panic: BINARY UPDATED BEFORE TRIGGER! UPGRADE "bluetiful" - in binary but not executed on chain

### ISSUE THREAD

**Issue by kobrien** [provenance-io/mainnet#10]
## Summary of Bug

Sentry node crashes in the middle of sync

```
9:09PM INF starting ABCI with Tendermint
9:09PM INF Starting multiAppConn service impl=multiAppConn module=proxy
9:09PM INF Starting localClient service connection=query impl=localClient module=abci-client
9:09PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
9:09PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
9:09PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
9:09PM INF Starting EventBus service impl=EventBus module=events
9:09PM INF Starting PubSub service impl=PubSub module=pubsub
9:09PM INF Starting IndexerService service impl=IndexerService module=txindex
9:09PM INF ABCI Handshake App Info hash="�\x04�վ��P�S܁\bp\x15�H(/g�ǲ~La�;�<�$" height=351901 module=consensus protocol-version=0 software-version=
9:09PM INF ABCI Replay Blocks appHeight=351901 module=consensus stateHeight=351901 storeHeight=351902
9:09PM INF Replay last block using real app module=consensus
9:09PM ERR BINARY UPDATED BEFORE TRIGGER! UPGRADE "bluetiful" - in binary but not executed on chain
panic: BINARY UPDATED BEFORE TRIGGER! UPGRADE "bluetiful" - in binary but not executed on chain

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker(0xc000e55f20, 0x10, 0xc001121590, 0x2547e40, 0xc000e77a80, 0x2588f40, 0xc000e00c70, 0xc0000c8ea0, 0x256f5c0, 0xc00011e150, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/x/upgrade/abci.go:84 +0x11a5
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.42.4/x/upgrade/module.go:127
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc000c1b2d0, 0x256f5c0, 0xc00011e150, 0x2588940, 0xc000ec2180, 0xb, 0x0, 0xc00133d9c0, 0xd, 0x55e9e, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/types/module/module.go:338 +0x1a2
github.com/provenance-io/provenance/app.(*App).BeginBlocker(...)
	github.com/provenance-io/provenance/app/app.go:639
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc000f676c0, 0xc001387fa0, 0x20, 0x20, 0xb, 0x0, 0xc00133d9c0, 0xd, 0x55e9e, 0x804506d, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/baseapp/abci.go:179 +0x658
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc0011080c0, 0xc001387fa0, 0x20, 0x20, 0xb, 0x0, 0xc00133d9c0, 0xd, 0x55e9e, 0x804506d, ...)
	github.com/tendermint/tendermint@v0.34.10/abci/client/local_client.go:274 +0xfa
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc000b74fd0, 0xc001387fa0, 0x20, 0x20, 0xb, 0x0, 0xc00133d9c0, 0xd, 0x55e9e, 0x804506d, ...)
	github.com/tendermint/tendermint@v0.34.10/proxy/app_conn.go:81 +0x75
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x2570480, 0xc001108300, 0x257d480, 0xc000b74fd0, 0xc00000cf00, 0x2588b40, 0xc000f053c0, 0x1, 0xc00133b520, 0x20, ...)
	github.com/tendermint/tendermint@v0.34.10/state/execution.go:307 +0x51b
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000c1a850, 0xb, 0x0, 0xc00133c9b0, 0x8, 0xc00133c9c0, 0xd, 0x1, 0x55e9d, 0xc00133b520, ...)
	github.com/tendermint/tendermint@v0.34.10/state/execution.go:140 +0x165
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc0017c4270, 0xb, 0x0, 0xc00133c9b0, 0x8, 0xc00133c9c0, 0xd, 0x1, 0x55e9d, 0xc00133b520, ...)
	github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:503 +0x292
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0017c4270, 0xb, 0x0, 0xc00133c9b0, 0x8, 0xc00133c9c0, 0xd, 0x1, 0x55e9d, 0xc00133b520, ...)
	github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:416 +0xdb8
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0017c4270, 0x258d380, 0xc000178750, 0x1, 0x1)
	github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:268 +0x478
github.com/tendermint/tendermint/node.doHandshake(0x2588b40, 0xc000f053c0, 0xb, 0x0, 0xc00133c9b0, 0x8, 0xc00133c9c0, 0xd, 0x1, 0x55e9d, ...)
	github.com/tendermint/tendermint@v0.34.10/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000e248c0, 0x25655c0, 0xc000d07c20, 0xc000f04bf0, 0x25223a0, 0xc001598720, 0xc000f04de0, 0x2303ca8, 0xc000f052d0, 0x2570480, ...)
	github.com/tendermint/tendermint@v0.34.10/node/node.go:715 +0x1fc5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000ea5c60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x25794c0, 0xc000ddf930, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:244 +0x565
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000e69900, 0xc000ea5dc0, 0x0, 0x2, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:120 +0x1c8
github.com/spf13/cobra.(*Command).execute(0xc000e69900, 0xc000ea5da0, 0x2, 0x2, 0xc000e69900, 0xc000ea5da0)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000db5b80, 0x0, 0x0, 0xc000f22bc0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
github.com/provenance-io/provenance/cmd/provenanced/cmd.Execute(0xc000db5b80, 0x257cdc0, 0xc000df0ec0)
	github.com/provenance-io/provenance/cmd/provenanced/cmd/root.go:114 +0x315
main.main()
	github.com/provenance-io/provenance/cmd/provenanced/main.go:11 +0x2a
```

## Version

provenanceio/provenance:v1.3.0

## Steps to Reproduce

Have not reproduced yet, am going to wipe the node and re-launch, will update this ticket if the error occurs again

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kobrien** [comment]
downgraded version to 1.0.1, as per mainnet instructions.

will upgrade to 1.3.0 when upgrade height is hit
